In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
posts_df = pd.read_csv("data/posts.csv")

In [4]:
posts_df.head(3)

,uri,author_handle,author_did,text,created_at,reply_count,repost_count,quote_count,like_count,is_reply,reply_parent,keyword
0,at://did:plc:rrpnky2otfaua3goqxzlsg2q/app.bsky...,stevesteverers.whaleoilcandles.com,did:plc:rrpnky2otfaua3goqxzlsg2q,I think there's an expert on Twitter you can ask,2026-05-20T14:54:40.483Z,0,0,0,0,True,at://did:plc:4za4evmhsstfh3ex2o37weog/app.bsky...,twitter
1,at://did:plc:abfnjipu7xshc26mudmvripk/app.bsky...,ansel.tv,did:plc:abfnjipu7xshc26mudmvripk,"there's only one ""coffee hack"" you need & it's...",2026-05-20T14:54:37.896Z,1,0,0,0,False,NaN,twitter
2,at://did:plc:egnysgvogtrpyd57haol53sj/app.bsky...,thoughtpunks.com,did:plc:egnysgvogtrpyd57haol53sj,"PSA: This ain't Twitter. So: \n\n1) Your ""Prog...",2026-05-20T14:54:37.493Z,0,0,0,1,False,NaN,twitter

In [5]:
posts_df.describe()

        reply_count  repost_count   quote_count    like_count
count  14165.000000  14165.000000  14165.000000  14165.000000
mean       1.115708      2.676032      0.271444     16.421532
std       17.730914     84.166718      6.926661    315.295755
min        0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.000000      1.000000
75%        1.000000      0.000000      0.000000      4.000000
max     1996.000000   9369.000000    641.000000  32757.000000

In [6]:
posts_df['is_reply'].value_counts()

is_reply
False    7542
True     6623
Name: count, dtype: int64

In [16]:
posts_df['reply_count'].value_counts()

reply_count
0       8304
1       4081
2        892
3        316
4        142
5        107
6         59
7         44
10        25
8         24
9         20
11        18
12        15
13        13
20         9
14         9
19         8
15         7
16         7
22         4
33         3
31         3
25         3
41         3
27         3
17         3
26         3
28         2
21         2
23         2
18         2
83         2
56         2
29         2
65         2
48         1
106        1
50         1
131        1
58         1
43         1
116        1
140        1
505        1
44         1
57         1
36         1
24         1
67         1
61         1
68         1
54         1
30         1
64         1
1996       1
135        1
93         1
60         1
62         1
Name: count, dtype: int64

In [7]:
threads = {}

for index, row in posts_df[posts_df['is_reply']].iterrows():
    parent = row['reply_parent']
    if parent not in threads:
        threads[parent] = []
    threads[parent].append(row)

In [ ]:
threads

{'at://did:plc:4za4evmhsstfh3ex2o37weog/app.bsky.feed.post/3mmc4xwfv4s26': [uri              at://did:plc:rrpnky2otfaua3goqxzlsg2q/app.bsky...
  author_handle                   stevesteverers.whaleoilcandles.com
  author_did                        did:plc:rrpnky2otfaua3goqxzlsg2q
  text              I think there's an expert on Twitter you can ask
  created_at                                2026-05-20T14:54:40.483Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:4za4evmhsstfh3ex2o37weog/app.bsky...
  keyword                                                    twitter
  Name: 0, dtype: object],
 'at://did:plc:azxqms6di5kwzfyngxnwwrzp/app.bsky.feed.post/3mmbxuazsvs2p': [uri              at://did:plc:glwsj5kbylpti4qwthwfrqcs/app.bsky...
  author_handle                             eveningffxiv.bsky.social
  author_did                        did:plc:glwsj5kbylpti4qwthwfrqcs
  text             Hard agree. I barely use my twitter for anythi...
  created_at                                2026-05-20T14:53:53.265Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       1
  is_reply                                                      True
  reply_parent     at://did:plc:azxqms6di5kwzfyngxnwwrzp/app.bsky...
  keyword                                                    twitter
  Name: 4, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ugjmws2t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             TWITTER AND YOUTUBE, TUMBLR AND AO3 ALSO GOT B...
  created_at                                2026-05-20T14:53:13.714Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 5, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ugjjz22t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             GUYS HAVE ABOUT THE REAL WORLD, YOUR LIFE BECA...
  created_at                                2026-05-20T14:53:13.712Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 6, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ue7lsc2t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             'BEATLES AND LEWIS HAMILTON' WELL OKAY THIS AB...
  created_at                                2026-05-20T14:53:13.699Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 7, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ue7kt22t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             SERIES TO HOSTING FAN CAFES FOR THE BEATLES AN...
  created_at                                2026-05-20T14:53:13.698Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 8, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ue7hvc2t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             TWITTER WHERE IT LOOKS LIKE THEY POST UP AI LO...
  created_at                                2026-05-20T14:53:13.696Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 9, dtype: object],
 'at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky.feed.post/3mmc5ue7gw22t': [uri              at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  author_handle                         assholejonesoped.bsky.social
  author_did                        did:plc:aaawu3nm7b5yfdfslc5svvag
  text             THIS USER ABSOLUTELY DOESN’T LOOK LIKE THEY HA...
  created_at                                2026-05-20T14:53:13.695Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:aaawu3nm7b5yfdfslc5svvag/app.bsky...
  keyword                                                    twitter
  Name: 10, dtype: object],
 'at://did:plc:zb6f27emrgxjguima2axgqm7/app.bsky.feed.post/3mmc52curvs2u': [uri              at://did:plc:gusr5s6aq6wf3n5eawhfopst/app.bsky...
  author_handle                                 bigwheel.bsky.social
  author_did                        did:plc:gusr5s6aq6wf3n5eawhfopst
  text             had to go find this in my files. some people w...
  created_at                                2026-05-20T14:53:11.562Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:zb6f27emrgxjguima2axgqm7/app.bsky...
  keyword                                                    twitter
  Name: 11, dtype: object],
 'at://did:plc:kybgt4j3o7i7nd3aci7ldwfv/app.bsky.feed.post/3mmc5np4rnk2k': [uri              at://did:plc:xf53ujprnmfktaxb77fztor6/app.bsky...
  author_handle                         electricfelix.eurosky.social
  author_did                        did:plc:xf53ujprnmfktaxb77fztor6
  text             Noah is one of those boss levelers still on tw...
  created_at                                2026-05-20T14:52:08.766Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:kybgt4j3o7i7nd3aci7ldwfv/app.bsky...
  keyword                                                    twitter
  Name: 15, dtype: object],
 'at://did:plc:easdcdpej2skorweyfza6ily/app.bsky.feed.post/3mmc5kneo222e': [uri              at://did:plc:easdcdpej2skorweyfza6ily/app.bsky...
  author_handle                                    zzyzx.bsky.social
  author_did                        did:plc:easdcdpej2skorweyfza6ily
  text             www.snopes.com/fact-check/t...\n\nIf you misse...
  created_at                                2026-05-20T14:50:30.476Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:easdcdpej2skorweyfza6ily/app.bsky...
  keyword                                                    twitter
  Name: 18, dtype: object],
 'at://did:plc:vlvj73mwqtw5s7kua6vjlmgx/app.bsky.feed.post/3mmazeqefrc2x': [uri              at://did:plc:ie4sg7z6v3mr2oxv7sfpf2ws/app.bsky...
  author_handle                           sylwritesstuff.bsky.social
  author_did                        did:plc:ie4sg7z6v3mr2oxv7sfpf2ws
  text             Me, happier and happier to have completely rem...
  created_at                                2026-05-20T14:47:30.073Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:vlvj73mwqtw5s7kua6vjlmgx/app.bsky...
  keyword                                                    twitter
  Name: 24, dtype: object,
  uri              at://did:plc:qwwqg2soygrkxr7gfenypfq6/app.bsky...
  author_handle                            ineffablejess.bsky.social
  author_did                        did:plc:qwwqg2soygrkxr7gfenypfq6
  text                                      Me scrolling on Twitter:
  created_at                                2026-05-20T04:51:19.214Z
  reply_count                                                      1
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       7
  is_reply                                                      True
  reply_parent     at://did:plc:vlvj73mwqtw5s7kua6vjlmgx/app.bsky...
  keyword                                                    twitter
  Name: 996, dtype: object],
 'at://did:plc:wtukkd3rxerinpxb6rd3aucn/app.bsky.feed.post/3mmc5i7yxf22x': [uri              at://did:plc:wtukkd3rxerinpxb6rd3aucn/app.bsky...
  author_handle                                 applexxe.bsky.social
  author_did                        did:plc:wtukkd3rxerinpxb6rd3aucn
  text             i hope no one from twitter finds this randomly...
  created_at                                2026-05-20T14:46:28.883Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:wtukkd3rxerinpxb6rd3aucn/app.bsky...
  keyword                                                    twitter
  Name: 27, dtype: object],
 'at://did:plc:7p3hjfingkqhwab2nmdj3w2a/app.bsky.feed.post/3mmbygnz5622f': [uri              at://did:plc:ctgitenyegwg3dzup23ffwa3/app.bsky...
  author_handle                                   mizati.bsky.social
  author_did                        did:plc:ctgitenyegwg3dzup23ffwa3
  text             I dumped Twitter a while ago.  It was a good d...
  created_at                                2026-05-20T14:46:04.381Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:7p3hjfingkqhwab2nmdj3w2a/app.bsky...
  keyword                                                    twitter
  Name: 28, dtype: object],
 'at://did:plc:f7xpfjsdiinb7g3x3jm2rfdt/app.bsky.feed.post/3mmbpqvmq6k2h': [uri              at://did:plc:tqmlgyjsdg4sjm2aqyj4a5ub/app.bsky...
  author_handle                              thenwmagpie.bsky.social
  author_did                        did:plc:tqmlgyjsdg4sjm2aqyj4a5ub
  text             Yep.  A lot of Black women on Twitter warned s...
  created_at                                2026-05-20T14:45:54.637Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       1
  is_reply                                                      True
  reply_parent     at://did:plc:f7xpfjsdiinb7g3x3jm2rfdt/app.bsky...
  keyword                                                    twitter
  Name: 29, dtype: object],
 'at://did:plc:v2hgx4ik7c54chnyfus4vuxv/app.bsky.feed.post/3mmc4yhvzwk2b': [uri              at://did:plc:ff6kddfj7nzxmaqwfx4rxlid/app.bsky...
  author_handle                                laine4466.bsky.social
  author_did                        did:plc:ff6kddfj7nzxmaqwfx4rxlid
  text             Unfortunately there isn't an uncensored versio...
  created_at                                2026-05-20T14:44:06.800Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       1
  is_reply                                                      True
  reply_parent     at://did:plc:v2hgx4ik7c54chnyfus4vuxv/app.bsky...
  keyword                                                    twitter
  Name: 32, dtype: object],
 'at://did:plc:uvm7ghe25nimhounygoak5b2/app.bsky.feed.post/3mm7lrlanss2o': [uri              at://did:plc:5q4lfnk5ean6idy27agligtp/app.bsky...
  author_handle                                  timamor.bsky.social
  author_did                        did:plc:5q4lfnk5ean6idy27agligtp
  text             I think threads is in the same murky categorie...
  created_at                                2026-05-20T14:42:58.485Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:uvm7ghe25nimhounygoak5b2/app.bsky...
  keyword                                                    twitter
  Name: 33, dtype: object],
 'at://did:plc:dkibknn7zo34yr4q4shyvaxi/app.bsky.feed.post/3mmc4vwsgec2h': [uri              at://did:plc:i7vam6ghzij4wikvs4grpbk6/app.bsky...
  author_handle                         djdresden.clownpenis.monster
  author_did                        did:plc:i7vam6ghzij4wikvs4grpbk6
  text             Lost all respect for him when he blocked me on...
  created_at                                2026-05-20T14:41:25.682Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:dkibknn7zo34yr4q4shyvaxi/app.bsky...
  keyword                                                    twitter
  Name: 34, dtype: object],
 'at://did:plc:5q4lfnk5ean6idy27agligtp/app.bsky.feed.post/3mmc4zpqoyk2e': [uri              at://did:plc:5q4lfnk5ean6idy27agligtp/app.bsky...
  author_handle                                  timamor.bsky.social
  author_did                        did:plc:5q4lfnk5ean6idy27agligtp
  text             But it could be that I’m just staying out of h...
  created_at                                2026-05-20T14:41:18.835Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       1
  is_reply                                                      True
  reply_parent     at://did:plc:5q4lfnk5ean6idy27agligtp/app.bsky...
  keyword                                                    twitter
  Name: 35, dtype: object],
 'at://did:plc:7ozaybixkzo4old4bvzafk7i/app.bsky.feed.post/3mmbzbckbb22m': [uri              at://did:plc:2qsynxreiydakokatzugd6es/app.bsky...
  author_handle                             querdenkenno.bsky.social
  author_did                        did:plc:2qsynxreiydakokatzugd6es
  text             Den Scheißdreck hatte ich schon auf Twitter ge...
  created_at                                2026-05-20T14:37:56.449Z
  reply_count                                                      0
  repost_count                                                     0
  quote_count                                                      0
  like_count                                                       0
  is_reply                                                      True
  reply_parent     at://did:plc:7ozaybixkzo4old4bvzafk7i/app.bsky...
  keyword                                                    twitter
  Name: 39, dtype: object],
 'at://did:plc:erg7oicr5rlevgmmpi7eibez/app.bsky.feed.post/3mmc4q25avs2j': [uri              at://did:plc:erg7oicr5rlevgmmpi7eibez/app.bsky...
  author_handle                                pawzmosis.bsky.social
  author_did                        did:plc:erg7oicr5rlevgmmpi7eibez
  text             but nooooo this site is SO much better than tw...
  created_at                                2026-05-20T14:37:41.202Z
  reply_count                                                      1

In [17]:
len(threads)

6070

In [ ]:
reply_groups = posts_df[posts_df["is_reply"]].groupby("reply_parent")

In [35]:
reply_groups.size()

reply_parent
at://did:plc:222p42fegwhwfyrc3gqam76j/app.bsky.feed.post/3lpkfisyyf22k    1
at://did:plc:222rnvnta2lbl364bog2plxw/app.bsky.feed.post/3lrg72y5zkc2r    1
at://did:plc:222rnvnta2lbl364bog2plxw/app.bsky.feed.post/3mcaqnlliik2u    1
at://did:plc:222rnvnta2lbl364bog2plxw/app.bsky.feed.post/3me24krbdbk2o    1
at://did:plc:222rnvnta2lbl364bog2plxw/app.bsky.feed.post/3mfs3e3lwmc2i    1
                                                                         ..
at://did:plc:zylv4gasp2fj2f6zqnc6n7zk/app.bsky.feed.post/3mm4r3r5gis2s    1
at://did:plc:zys3icn5r7d3m476di4ttao6/app.bsky.feed.post/3mcch4r3o7k27    1
at://did:plc:zzp52njycx34ecru4tgzwk6v/app.bsky.feed.post/3mmb4zxiznc2a    1
at://did:web:didd.uk/app.bsky.feed.post/3mm3n6grfuc2r                     1
at://did:web:jheya.anaproto.xyz/app.bsky.feed.post/3lihsojwpkc2m          1
Length: 6070, dtype: int64